version: 2
updates:
  - package-ecosystem: "github-action" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
