name: FTP Deployment

on:
  push:
    branches:
      - main
      - chore/deployment

env:
  node: 20

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node }}
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Clean Distribution Directory
        run: npm run ci:clean

      - name: Build Application
        run: npm run ci:build

      - name: 📂 Deploy over FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: atlas-al.de
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /
          local-dir: ./dist/
